global:
  timezone: UTC
  puid: "1000"
  pgid: "1000"
  nodeSelector: {}

sonarr:
  enabled: false
  image:
    repository: lscr.io/linuxserver/sonarr
    pullPolicy: IfNotPresent
    tag: latest
  
  persistence:
    config:
      enabled: true
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi
      hostPath: ""
    mounts:
      - name: media
        pvcName: existing-media-pvc
        mountPath: /media
  
  service:
    type: ClusterIP
    port: 8989

radarr:
  enabled: false
  image:
    repository: lscr.io/linuxserver/radarr
    pullPolicy: IfNotPresent
    tag: latest
  
  persistence:
    config:
      enabled: true
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi
      hostPath: ""
    mounts:
      - name: media
        pvcName: existing-media-pvc
        mountPath: /media
  
  service:
    type: ClusterIP
    port: 7878

jackett:
  enabled: false
  image:
    repository: lscr.io/linuxserver/jackett
    pullPolicy: IfNotPresent
    tag: latest
  
  persistence:
    config:
      enabled: true
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi
      hostPath: ""
  
  service:
    type: ClusterIP
    port: 9117
